### ISSUE TITLE
After changing the source, "mutmut show NUM" does nothing

### ISSUE THREAD

**Issue by nedbat** [boxed/mutmut#101]
I ran mutmut on cogapp/cogapp.py, and changed that file based on one of the mutations.  Then trying to look at other mutations did nothing:
```
$ mutmut show 111

$
```
No message, no output other than a single blank line.  `mutmut results` still shows all the mutant ids as it did before the change.

**Comment by boxed** [comment]
Hmm... Could you maybe supply me with the SHA before and after the change? I've been searching for a reproduction scenario for this bug but I haven't nailed it down yet. 

To solve the problem just running "mutmut run" should update the cache I hope.

**Comment by nedbat** [comment]
Hmm, I tried to go back and do it again, and I'm not sure what I did.... I'll pay closer attention next time.

**Comment by boxed** [comment]
That is unfortunately my experience as well! I'm keeping my fingers crossed.

**Comment by boxed** [comment]
Well this was surprisingly easy to reproduce when I understood! You just add a line at some place above the mutant you want to show with `mutmut show <number>`.

The underlying issue is that the mutmut cache isn't updated with the new source code reality first, so the line numbers are off, and that makes the mutation not do anything. The workaround is to do `mutmut run` and cancel it immediately, because that command corrects the cache when it starts.
