### ISSUE TITLE
Docs clarification ?

### ISSUE THREAD

**Issue by m4r35n357** [boxed/mutmut#141]
How do timeouts work?

The help text says timeouts happen after 10 X the baseline, but AFAICT (from source) the baseline is zero.

I only ask because experimentation takes a long time . . . .

**Comment by boxed** [comment]
https://github.com/boxed/mutmut/blob/master/mutmut/__main__.py#L323

Should not be zero

**Comment by m4r35n357** [comment]
I was referring to this line and the following one:
[(https://github.com/boxed/mutmut/blob/1d39a91c0468c79285bfb841ba4e8ec6fe20aa99/mutmut/__main__.py#L184)](url)

To quote the output of mutmut:

> ⏰ Timeout.          Test suite took 10 times as long as the baseline so were killed.

After all, if the baseline is zero, it matters not what the mutliplier is!
So, as I interpret this, all my tests should time out (and they don't) if this is not overridden somewhere.  I would like to set my own values for base and multiplier, but I can't find what the (effective) defaults are.

So, if not zero, can you help me understand what the default base and multiplier values are, if they are not as specified in the line I pointed to above?

**Comment by boxed** [comment]
Hmm.. well the next line does say it's 2x by default, not 10x so that's something wrong at least.

But no, it's not zero. test-time-base is for use in CI and tests in mutmut where it ADDS to the timeout. It's useful if you have a very fast test suite that has a big variance (as in more than 2x). In those cases you can add a constant to the base time to avoid mutmut thinking things time out when they don't. test-time-base is not the same as the baseline: https://github.com/boxed/mutmut/blob/master/mutmut/__main__.py#L561

**Comment by m4r35n357** [comment]
OK thanks for answering, I have my hands full actually testing my tests to fully understand mutmut ;)
I have found that in my case these (intermittent) timeouts seem to happen because I have _too many_ failing tests for a particular mutant!
Anyhow, it takes about five minutes to run mutmut, so I will just have to do this in the background . . . adding a second (I assume) at a time (please let me know if they are microseconds!).

**Comment by boxed** [comment]
They are seconds :P

**Comment by m4r35n357** [comment]
Cheers!
