### ISSUE TITLE
Even if `tests-dir` is specified, pytest still collects tests on all the repository

### ISSUE THREAD

**Issue by SdgJlbl** [boxed/mutmut#165]
Long story short, I have a repository which is quite packed, including sub-directory that have their own tests sub-sub-directory. 

When I run `mutmut run --tests-dir tests/unit/`, the first step still runs `python -m pytest -x`, which fails on my use case (because of the tests sub-sub-directories which should not be executed). 

I would have expected mutmut to run `python -m pytest -x tests/unit/` instead. 

Is there a point to run pytest on the whole repository or is it an oversight?

(version 1.6.0)

**Comment by boxed** [comment]
Yea it's surprising. It's a side effect of mutmut trying very hard not to know anything about the internals or surfaces of test systems. But I do need to know where the code is, that's what tests dirs is for. You'll have to change the runner command too I'm afraid.

**Comment by SdgJlbl** [comment]
That's what I did, but I was wondering if it was the intended behaviour or if it is was a bug. 
Just letting you know in case of :)

**Comment by boxed** [comment]
It used to be that mutmut put the tests die in the argument list but that didn't work for other runners so that became a bug. 

Good! I hope you otherwise got up and running! I find that it's ofteb easier to move some code out of the project for mutation testing. In my case I work on a really big project so just the test collection is pretty slow. 

You can also turn off assertion rewriting to speed it up.

**Comment by SdgJlbl** [comment]
Oh, ok, thanks for the explanation, that makes sense :) 

Else, it's my first experience with mutation testing, and so far mutmut is running great and has a great starting guide 👍 

Thanks for the tip, I'll probably end up copying the repo and removing all the boilerplate files. 
And thank you for maintaining mutmut!

**Comment by boxed** [comment]
Glad to hear it! 

If you have social media followers or a blog spread the word! :)
