### ISSUE TITLE
Target a single function or class

### ISSUE THREAD

**Issue by cleder** [boxed/mutmut#202]
Would it be possible to add a parameter to target only a single class or function for the mutations e.g.
`mypackage.mymodule.myfunction`

Rationale:
When working with a large codebase the mutations take a long time. It would be beneficial if I could test only the highest value functions, or tackle a module class by class.

**Comment by boxed** [comment]
This would be very good yes. I have had to work around this by lifting out the function I wanted to mutation test and then reinsert the result back into the code base. 

Unfortunately, even if mutmut supported this feature and one used the coverage selection, it would still be very slow in a big code base due to pytest collection overhead. 

I have ideas for a total redesign (maybe even rewrite) of mutmut to handle this, plus paralell execution, and way faster execution. But life and work has higher priority I'm afraid.

**Comment by cleder** [comment]
OK, no problem. I think I can work around with just testing specific files for now. I will use something like:
```
files_to_mutate = ['foo.py', 'bar.py']

def pre_mutation(context):
    if context.filename not in files_to_mutate:
        context.skip = True
```
