### ISSUE TITLE
Tests not run after cancel and restart

### ISSUE THREAD

**Issue by awgymer** [boxed/mutmut#334]
My initial `mutmut` run was killed midway through step 2. The output suggested it was about 250/1700 mutants through. On resume it started on 77/324 and stopped after running 324. 

mutmut results then showed errors (well, passing tests!) for errors with ids well into the 1000s and examining some of the supposed failures they appear to be mutators that would in fact break tests.

**Comment by boxed** [comment]
I just released mutmut 3, which is a big rewrite. I believe this issue no longer applies anymore. Feel free to reopen it if it still exists.

**Comment by shoofar** [comment]
This is still present in mutmut 3.6.0 - the rewrite didn't fix it (or reintroduced an equivalent bug). Reopening per your invitation above; happy for a maintainer to actually toggle the state since I don't have permission to.

**Reproduction (3.6.0):**
```
mutmut run --max-children 2      # kill partway through, e.g. `timeout 30 mutmut run --max-children 2`
mutmut run --max-children 2      # "resume" - starts counting from 0/N again
```
The second invocation re-tests every mutant instead of skipping the ones already resolved, and can end up taking *longer* in total than a single clean run.

**Root cause:** `create_mutants_for_file` in `src/mutmut/__main__.py` does persist each mutant's result incrementally to `mutants/<file>.meta` (`SourceFileMutationData.save()`), and the main loop does correctly skip a mutant whose result is already known:
```python
# Rerun mutant if it's explicitly mentioned, but otherwise let the result stand
if not mutant_names and result is not None:
    continue
```
but `create_mutants_for_file` itself unconditionally wipes `exit_code_by_key` back to `None` on *every* invocation, before that check ever gets a chance to matter - in both of its code paths:
- when source is unchanged since the mutants were generated (`source_mtime < mutant_mtime`), it explicitly resets every value to `None` and saves
- when mutations are (re)generated, a fresh all-`None` dict is written

So the incremental persistence exists, but gets undone on the very next `mutmut run` regardless of whether anything actually changed.

**Suggested fix** (minimal, only touches the "source genuinely unchanged" branch - the regeneration branch is correct as-is):
```diff
         if source_mtime < mutant_mtime:
-            # reset the mutation stats
-            source_file_mutation_data = SourceFileMutationData(path=filename)
-            source_file_mutation_data.load()
-            for key in source_file_mutation_data.exit_code_by_key:
-                source_file_mutation_data.exit_code_by_key[key] = None
-            source_file_mutation_data.save()
-
             return FileMutationResult(unmodified=True)
```

**Empirical verification with this fix applied**, `--max-children 8`, 182-mutant target:
- Clean run: 70.5s
- Killed at ~30s (44/182 already checkpointed in `mutants/*.meta`)
- Resume: 48.2s to finish the remaining 138, identical final result (157 killed / 23 survived)

Before the fix, the same kill-then-resume pattern took *longer* than starting over (86s vs a 68s clean baseline on a similar run) - i.e. resume was actively counterproductive, not just a no-op.

Happy to open a PR with this change plus a regression test covering both branches (unchanged-source preserves results / genuinely-changed-source still regenerates fresh) if that's useful.
