### ISSUE TITLE
Indicate result via exit code

### ISSUE THREAD

**Issue by ulope** [boxed/mutmut#49]
Currently mutmut `run` and `result` always exits with code `0`.

It would be very useful (e.g. for inclusion in CI systems) if both could give a return code depending on the type of found issues.

**Comment by boxed** [comment]
What would be a good exit code scheme? 0 is normally success, and if `run` and `result` don't fail then it doesn't make sense to me to exit with a non-zero exit code...

Can I suggest what you really want is a porcelain format of `result`? So you can just `mutmut result-machine-readable | wc -l` to get the number of survived mutants for use by CI?

**Comment by nklapste** [comment]
In a experimental branch I accomplished making a return code similar to how pylint works:

```python


def compute_return_code(config, exception=None):
    """Compute an error code similar to how pylint does. (using bit OR)

    The following output status codes are available for mutmut:
     * 0 if all mutants were killed (OK_KILLED)
     * 1 if a fatal error occurred
     * 2 if one or more mutants survived (BAD_SURVIVED)
     * 4 if one or more mutants timed out (BAD_TIMEOUT)
     * 8 if one or more mutants caused tests to take twice as long (OK_SUSPICIOUS)
     status codes 1 to 8 will be bit-ORed so you can know which different
     categories has been issued by analysing the mutmut output status code

    :param exception:
    :type exception: Exception
    :param config:
    :type config: Config

    :return: a integer noting the return status of the mutation tests.
    :rtype: int
    """
    code = 0
    if exception is not None:
        code = code | 1
    if config.surviving_mutants > 0:
        code = code | 2
    if config.surviving_mutants_timeout > 0:
        code = code | 4
    if config.suspicious_mutants > 0:
        code = code | 8
    return code

```
However this branch `feature/refactoring` is out of date with master and currently does not work correctly with the new caching system.

**Comment by boxed** [comment]
That sounds pretty good too. I just would like to know what the use case is before taking a decision here. So @ulope what are your thoughts? And @blueyed maybe?

**Comment by jmdacruz** [comment]
In order to make the output machine readable, most testing tools already use JUnit's XML format. For instance, `pytest` has support for doing this with the `--junitxml` parameter: https://docs.pytest.org/en/latest/usage.html#creating-junitxml-format-files. I believe that most CI solutions include support for interpreting JUnit XML files and deriving test results out of them, instead of relying just on exit codes. The challenge then would be how to structure the "test suites" in the output: You can go with a flat structure having one entry for "surviving", one for "timeouts", and one for "suspicious", or having one entry per each mutation with the result of the test for each case (I like this approach better). The JUnit XML format also allows you to include a description of the test result and/or logs, so you can include the diff of the mutant there (this can then automatically be rendered to HTML by the CI tools)

About the exit code, I think it could be similar to what `coverage` does with `--fail-under`. This way you can fine tune based on your environment, maybe using percentages? (e.g., 0% surviving mutants, less than 10% suspicious mutants, etc.)

**Comment by jmdacruz** [comment]
I took the liberty to create an experimental PR (#55) to test this concept

**Comment by boxed** [comment]
@ulope The junit output is merged now... is this enough for your use case?

**Comment by ulope** [comment]
@boxed Hm well, it isn't ideal. I guess it would be possible to parse the junit result but that's probably even more work than parsing the user facing output.

An exit code still is the most natural way CI/CD systems are informed about the success / failure of steps.

**Comment by boxed** [comment]
@ulope ok, thanks for your feedback. Then I suggest we do what @nklapste suggests. 

@nklapste can you maybe make a PR with just this change?

**Comment by nklapste** [comment]
> 
> 
> @ulope ok, thanks for your feedback. Then I suggest we do what @nklapste suggests.
> 
> @nklapste can you maybe make a PR with just this change?

Most definitely! Should be pressed out by the end of the day!

**Comment by boxed** [comment]
Great! I'll add you as a contributor as soon as I get time btw. You're clearly over my limit of two good PRs by now :P

**Comment by ulope** [comment]
Awesome, thanks a lot!

**Comment by boxed** [comment]
I've rolled a 1.2.0 release that includes this now.
